Theatre/Theatre/Models/Membership.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Threading.Tasks;

namespace Theatre.Models
{
    public class Membership
    {
        [Key] public int ID { get; set; }

        [Required(ErrorMessage = "Поле обязательно")]
        [DisplayName("Стоимость абонемента (₽)")]
        [Range(0, 100000, ErrorMessage = "Значение должно быть в пределе от 0 до 100000")]
        public double Price { get; set; }

        [DisplayName("Жанр")]
        public string Genre { get; set; }
        [DisplayName("Автор")]
        [AllowNull]
        public int? AuthorID { get; set; }
        [DisplayName("Автор")]
        public Author Author { get; set; }
    }
}

Theatre/Theatre/Controllers/MembershipController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Theatre.Models;

namespace Theatre.Controllers
{
    public class MembershipController : Controller
    {
        private readonly DatabaseContext _context;

        public MembershipController(DatabaseContext context)
        {
            _context = context;
        }


        public IActionResult Index(int role)
        {
            ViewData["AuthorID"] = new SelectList(_context.Authors, "ID", "FullName");
            ViewData["CurrentRole"] = role;
            var databaseContext = _context.Memberships.Include(m => m.Author);
            MembershipIndex membershipIndex = new MembershipIndex { Memberships = databaseContext.ToList(), CurrentRole = role};
            return View(membershipIndex);
        }


        [HttpPost]
        public async Task<IActionResult> Create(MembershipIndex membershipIndex)
        {
            Membership membership = membershipIndex.Membership;
            ViewData["CurrentRole"] = membershipIndex.CurrentRole;
           
            if (ModelState.IsValid)
            {
                _context.Memberships.Add(membership);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AuthorID"] = new SelectList(_context.Authors, "ID", "FullName", membership.AuthorID);
            membershipIndex.Memberships = _context.Memberships.ToList();
            return View(nameof(Index), membershipIndex);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var membership = await _context.Memberships.FindAsync(id);

            ViewData["AuthorID"] = new SelectList(_context.Authors, "ID", "FullName", membership.AuthorID);
            if (membership == null)
            {
                return NotFound();
            }
      
            return View(membership);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("ID, Price, Genre, AuthorID")] Membership membership)
        {
            if (id != membership.ID)
            {
                return NotFound();
            }
            ViewData["AuthorID"] = new SelectList(_context.Authors, "ID", "FullName", membership.AuthorID);
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Memberships.Update(membership);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MembershipExists(membership.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                MembershipIndex membershipIndex = new MembershipIndex { Memberships = _context.Memberships.Include(e => e.Author) };
                return Json(new { isValid = true, html = Helper.RenderRazorViewToString(this, "Index", membershipIndex) });
            }

            return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "Edit", membership) });
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var membership = await _context.Memberships
                .Include(m => m.Author)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (membership == null)
            {
                return NotFound();
            }

            _context.Memberships.Remove(membership);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MembershipExists(int id)
        {
            return _context.Memberships.Any(e => e.ID == id);
        }
    }
}

Theatre/Theatre/Views/Membership/Edit.cshtml
@model Theatre.Models.Membership

@{
    ViewData["Title"] = "Изменение абонемента";
    Layout = null;
}

<div class="container">
    <div class="col-md-12">
        <form asp-action="Edit" asp-route-id="ID" onsubmit="return jQueryAjaxPost(this);">
            >
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <select class="form-control" asp-for="Genre">
                    <option selected value="@null">_</option>
                    <option value="Комедия">Комедия</option>
                    <option value="Водевиль">Водевиль</option>
                    <option value="Мелодрама">Мелодрама</option>
                    <option value="Монодрама">Монодрама</option>
                    <option value="Мюзикл">Мюзикл</option>
                    <option value="Пародия">Пародия</option>
                    <option value="Трагикомедия">Трагикомедия</option>
                    <option value="Драма">Драма</option>
                </select>
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AuthorID" class="control-label"></label>
                <select asp-for="AuthorID" class="form-control" asp-items="ViewBag.AuthorID"> 
                    <option selected value="@null">_</option>
                </select>
                <span asp-validation-for="AuthorID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-primary btn-block" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Theatre/Theatre/Views/Membership/Index.cshtml
@model MembershipIndex

@{
    ViewData["Title"] = "Абонементы";
}

<div class="container">
    <div id="index">
        <h1 class="text-center" style="margin-bottom:8px;">Абонементы</h1>
        <div class="row">
            <div class="col-sm-9">
                <table class="table text-center">
                    <thead>
                        <tr>
                            <th>
                                Стоимость абонемента (₽)
                            </th>
                            <th>
                                Жанр
                            </th>
                            <th>
                                Автор
                            </th>
                            <th>Действия</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Memberships)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Price)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Genre)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Author.FullName)
                                </td>
                                <td>
                                    <a onclick="showInPopup('@Url.Action("Edit", "Membership", new { id = item.ID}, Context.Request.Scheme)',
                            'Изменение абонемента')" class="btn btn-success text-white">Изменить</a>
                                    <a asp-action="Delete" asp-route-id="@item.ID" class="btn btn-danger text-white">Удалить</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>

            </div>
            <div class="col-sm-3">
                <form asp-action="Create" class="col-md-12">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="@Model.Membership.Price" class="control-label"></label>
                        <input asp-for="@Model.Membership.Price" class="form-control" />
                        <span asp-validation-for="@Model.Membership.Price" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.Membership.Genre" class="control-label"></label>
                        <select class="form-control" asp-for="@Model.Membership.Genre">
                            <option selected value="@null">_</option>
                            <option value="Комедия">Комедия</option>
                            <option value="Водевиль">Водевиль</option>
                            <option value="Мелодрама">Мелодрама</option>
                            <option value="Монодрама">Монодрама</option>
                            <option value="Мюзикл">Мюзикл</option>
                            <option value="Пародия">Пародия</option>
                            <option value="Трагикомедия">Трагикомедия</option>
                            <option value="Драма">Драма</option>
                        </select>
                        <span asp-validation-for="@Model.Membership.Genre" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.Membership.AuthorID" class="control-label"></label>
                        <select asp-for="@Model.Membership.AuthorID" class="form-control" asp-items="ViewBag.AuthorID">
                            <option selected value="@null">_</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Добавить" class="btn btn-primary btn-block" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>