Theatre/Theatre/Models/Performance.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Threading.Tasks;

namespace Theatre.Models
{
    public class Performance
    {
        [Key] public int ID { get; set; }
        [DisplayName("Наименование")]
        [Required(ErrorMessage = "Наименование обязательно")]
        [RegularExpression(@"[a-zA-Zа-яА-Я0-9]+", ErrorMessage = "Наименование должно состоять из букв русского или английского алфавита или цифр 0-9")]
        public string Name { get; set; }
        [DisplayName("Дата и время премьеры")]
        [Date(ErrorMessage = "Дата должна быть больше текущей")]
        [Required(ErrorMessage = "Дата обязательна")]
        [DataType(DataType.DateTime, ErrorMessage = "Выберите дату")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd-mm-yyy-hh-mm}", ConvertEmptyStringToNull = true)]
        public string PremiereDate { get; set; }
        [DisplayName("Время начала")]
        [Date(ErrorMessage = "Дата должна быть больше текущей")]
        [Required(ErrorMessage = "Время начала обязательно")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd-mm-yyy}", ConvertEmptyStringToNull = true)]
        [DataType(DataType.DateTime, ErrorMessage = "Выберите дату")]
        public string BeginningTime { get; set; }
        [DisplayName("Тип спектакля")]
        [Required]
        public string PerformanceType { get; set; }

        [DisplayName("Жанр")]
        [Required]
        public string Genre { get; set; }

        [DisplayName("Автор")]
        [AllowNull]
        public int? AuthorID { get; set; }
        [DisplayName("Автор")]
        public Author Author { get; set; }

        public virtual List<Employee> Employees { get; set; } = new List<Employee>();
        public virtual List<Ticket> Tickets { get; set; } = new List<Ticket>();
    }

    public class DateAttribute : RangeAttribute 
    {
        public DateAttribute() : base(typeof(DateTime),
           DateTime.Now.ToShortDateString(),
           DateTime.Now.AddYears(100).ToShortDateString())
        { }
    }
}

Theatre/Theatre/Controllers/PerformanceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Theatre.Models;

namespace Theatre.Controllers
{
    public class PerformanceController : Controller
    {
        private readonly DatabaseContext _context;

        public PerformanceController(DatabaseContext context)
        {
            _context = context;
        }

        public IActionResult Index(int role)
        {
            ViewData["AuthorID"] = new SelectList(_context.Set<Author>(), "ID", "FullName");
            ViewData["CurrentRole"] = role;
            var databaseContext = _context.Performances.Include(p => p.Author);
            PerformanceIndex performanceIndex = new PerformanceIndex { Performances = databaseContext.ToList(), CurrentRole = role};
            return View(performanceIndex);
        }

     

        [HttpPost]
        public async Task<IActionResult> Create(PerformanceIndex performanceIndex)
        {
            ViewData["CurrentRole"] = performanceIndex.CurrentRole;
            if (ModelState.IsValid)
            {
                _context.Performances.Add(performanceIndex.Performance);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AuthorID"] = new SelectList(_context.Set<Author>(), "ID", "FullName", performanceIndex.Performance.AuthorID);          
            performanceIndex = new PerformanceIndex { Performances = _context.Performances.ToList() };
            return View(nameof(Index), performanceIndex);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var performance = await _context.Performances.FindAsync(id);
            if (performance == null)
            {
                return NotFound();
            }
            ViewData["AuthorID"] = new SelectList(_context.Set<Author>(), "ID", "FullName", performance.AuthorID);
            return View(performance);
        }


        [HttpPost]
        public async Task<IActionResult> Edit(int id, Performance performance)
        {
            if (id != performance.ID)
            {
                return NotFound();
            }
            ViewData["AuthorID"] = new SelectList(_context.Authors, "ID", "FullName", performance.AuthorID);
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(performance);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PerformanceExists(performance.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                PerformanceIndex performanceIndex = new PerformanceIndex { Performances = _context.Performances.Include(p => p.Author) };
                return Json(new { isValid = true, html = Helper.RenderRazorViewToString(this, "Index", performanceIndex) });
            }           
            return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "Edit", performance) });
        }

        [HttpGet]

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var performance = await _context.Performances
                .Include(p => p.Author)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (performance == null)
            {
                return NotFound();
            }

            _context.Performances.Remove(performance);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }


        private bool PerformanceExists(int id)
        {
            return _context.Performances.Any(e => e.ID == id);
        }
    }
}

Theatre/Theatre/Views/Performance/Edit.cshtml
@model Theatre.Models.Performance

@{
    ViewData["Title"] = "Изменение спектакля";
    Layout = null;
}

<div class="container">
    <div>
        <form asp-action="Edit" asp-route-id="ID" onsubmit="return jQueryAjaxPost(this);">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PremiereDate" class="control-label"></label>
                <input asp-for="PremiereDate" class="form-control" />
                <span asp-validation-for="PremiereDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BeginningTime" class="control-label"></label>
                <input asp-for="BeginningTime" class="form-control" />
                <span asp-validation-for="BeginningTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PerformanceType" class="control-label"></label>
                <select class="form-control" asp-for="PerformanceType">
                    <option selected value="Детский">Детский</option>
                    <option value="Молодежный">Молодежный</option>
                    <option value="Подростковый">Подростковый</option>
                    <option value="Взрослый">Взрослый</option>
                </select>
                <span asp-validation-for="PerformanceType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <select class="form-control" asp-for="Genre">
                    <option selected value="Драма">Драма</option>
                    <option value="Комедия">Комедия</option>
                    <option value="Водевиль">Водевиль</option>
                    <option value="Мелодрама">Мелодрама</option>
                    <option value="Монодрама">Монодрама</option>
                    <option value="Мюзикл">Мюзикл</option>
                    <option value="Пародия">Пародия</option>
                    <option value="Трагикомедия">Трагикомедия</option>
                </select>
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AuthorID" class="control-label"></label>
                <select asp-for="AuthorID" class="form-control" asp-items="ViewBag.AuthorID"></select>
                <span asp-validation-for="AuthorID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-primary btn-block" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Theatre/Theatre/Views/Performance/Index.cshtml
@model PerformanceIndex
@{
    ViewData["Title"] = "Спектакли";
}

<div class="container-fluid">
    <div id="index">
        <h1 class="text-center" style="margin-bottom:8px;">Спектакли</h1>
        <div class="row">
            <div class="col-sm-9">
                <table class="table text-center">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Performance.Name)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Performance.PremiereDate)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Performance.BeginningTime)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Performance.PerformanceType)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Performance.Genre)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Performance.Author)
                            </th>
                            <th>Действия</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Performances)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.PremiereDate)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.BeginningTime)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.PerformanceType)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Genre)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Author.FullName)
                                </td>
                                <td>
                                    <a onclick="showInPopup('@Url.Action("Edit", "Performance", new { id = item.ID}, Context.Request.Scheme)',
                            'Изменение сотрудника')" class="btn btn-success text-white">Изменить</a>
                                    <a asp-action="Delete" asp-route-id="@item.ID" class="btn btn-danger text-white">Удалить</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>

            </div>
            <div class="col-sm-3">
                <div class="col-md-12">
                    <form asp-action="Create">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="@Model.Performance.Name" class="control-label"></label>
                            <input asp-for="@Model.Performance.Name" class="form-control" />
                            <span asp-validation-for="@Model.Performance.Name" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="@Model.Performance.PremiereDate" class="control-label"></label>
                            <input asp-for="@Model.Performance.PremiereDate" class="form-control" />
                            <span asp-validation-for="@Model.Performance.PremiereDate" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="@Model.Performance.BeginningTime" class="control-label"></label>
                            <input asp-for="@Model.Performance.BeginningTime" class="form-control" />
                            <span asp-validation-for="@Model.Performance.BeginningTime" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="@Model.Performance.PerformanceType" class="control-label"></label>
                            <select class="form-control" asp-for="@Model.Performance.PerformanceType">
                                <option selected value="Детский">Детский</option>
                                <option value="Молодежный">Молодежный</option>
                                <option value="Подростковый">Подростковый</option>
                                <option value="Взрослый">Взрослый</option>
                            </select>
                            <span asp-validation-for="@Model.Performance.PerformanceType" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="@Model.Performance.Genre" class="control-label"></label>
                            <select class="form-control" asp-for="@Model.Performance.Genre">
                                <option selected value="Драма">Драма</option>
                                <option value="Комедия">Комедия</option>
                                <option value="Водевиль">Водевиль</option>
                                <option value="Мелодрама">Мелодрама</option>
                                <option value="Монодрама">Монодрама</option>
                                <option value="Мюзикл">Мюзикл</option>
                                <option value="Пародия">Пародия</option>
                                <option value="Трагикомедия">Трагикомедия</option>
                            </select>
                            <span asp-validation-for="@Model.Performance.Genre" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="@Model.Performance.AuthorID" class="control-label"></label>
                            <select asp-for="@Model.Performance.AuthorID" class="form-control" asp-items="ViewBag.AuthorID"></select>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Добавить" class="btn btn-primary btn-block" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>