Theatre/Theatre/Controllers/AuthorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Theatre.Models;

namespace Theatre.Controllers
{
    public class AuthorController : Controller
    {
        private readonly DatabaseContext _context;

        public AuthorController(DatabaseContext context)
        {
            _context = context;
        }

        public IActionResult Index(int role)
        {
            ViewData["CurrentRole"] = role;
            AuthorIndex authorIndex = new AuthorIndex { Authors = _context.Authors.ToList(),
            CurrentRole = role};
            return View(authorIndex);
        }

        [HttpPost]
        public async Task<IActionResult> Create(AuthorIndex authorIndex)
        {
            ViewData["CurrentRole"] = authorIndex.CurrentRole;
            if (ModelState.IsValid)
            {
                _context.Add(authorIndex.Author);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index), authorIndex);
            }

            authorIndex.Authors = _context.Authors.ToList();
            return View(nameof(Index), authorIndex);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var author = await _context.Authors.FindAsync(id);
            if (author == null)
            {
                return NotFound();
            }
            return View(author);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("ID, FullName")] Author author)
        {
            if (id != author.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(author);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AuthorExists(author.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                AuthorIndex authorIndex = new AuthorIndex { Authors = _context.Authors.ToList() };
                return Json(new { isValid = true, html = Helper.RenderRazorViewToString(this, "Index", authorIndex) });
            }
            return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "Edit", author) });
        }

        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var author = _context.Authors
                .FirstOrDefault(m => m.ID == id);
            if (author == null)
            {
                return NotFound();
            }
            _context.Authors.Remove(author);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
        private bool AuthorExists(int id)
        {
            return _context.Authors.Any(e => e.ID == id);
        }
    }
}

Theatre/Theatre/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Theatre.Models;

namespace Theatre.Controllers
{
    public class PostController : Controller
    {
        private readonly DatabaseContext _context;

        public PostController(DatabaseContext context)
        {
            _context = context;
        }

 
        public IActionResult Index(int role)
        {
            ViewData["CurrentRole"] = role;
            PostIndex postIndex = new PostIndex()
            {
                Posts = _context.Posts.ToList(),
                CurrentRole = role
            };

            return View(postIndex);
        }


        [HttpPost]
        public async Task<IActionResult> Create(PostIndex postIndex)
        {
            ViewData["CurrentRole"] = postIndex.CurrentRole;
            if (ModelState.IsValid)
            {
                _context.Add(postIndex.Post);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            postIndex.Posts = _context.Posts.ToList();
            return View(nameof(Index), postIndex);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts.FindAsync(id);
            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }


        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name")] Post post)
        {
            if (id != post.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(post);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PostExists(post.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                PostIndex postIndex = new PostIndex { Posts = _context.Posts.ToList() };
                return Json(new { isValid = true, html = Helper.RenderRazorViewToString(this, "Index", postIndex) });
            }
            return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "Edit", post) });
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts.FirstOrDefaultAsync(m => m.ID == id);
            if (post == null)
            {
                return NotFound();
            }

            _context.Posts.Remove(post);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }


        private bool PostExists(int id)
        {
            return _context.Posts.Any(e => e.ID == id);
        }
    }
}

Theatre/Theatre/Controllers/StageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Theatre.Models;

namespace Theatre.Controllers
{
    public class StageController : Controller
    {
        private readonly DatabaseContext _context;

        public StageController(DatabaseContext context)
        {
            _context = context;
        }

        public IActionResult Index(int role)
        {
            ViewData["CurrentRole"] = role;
            ViewData["EmployeeID"] = new SelectList(_context.Employees.Where(e => e.Role != (int)Roles.Admin), "ID", "FullName");
            ViewData["PerformanceID"] = new SelectList(_context.Performances, "ID", "Name");
            var databaseContext = _context.Stages.Include(s => s.Employee).Include(s => s.Performance).Include(e => e.Employee.Post);
            StageIndex stageIndex = new StageIndex {
                Stages = databaseContext.ToList(),
                CurrentRole = role
            };
            return View(stageIndex);
        }
     

        [HttpPost]
        public async Task<IActionResult> Create(StageIndex stageIndex)
        {
            Stage stage = stageIndex.Stage;

           
            ViewData["CurrentRole"] = stageIndex.CurrentRole;
            ViewData["EmployeeID"] = new SelectList(_context.Employees.Where(e => e.Role != (int)Roles.Admin), "ID", "FullName", stage.EmployeeID);
            ViewData["PerformanceID"] = new SelectList(_context.Performances, "ID", "Name", stage.PerformanceID);
     
            if (ModelState.IsValid)
            {
                _context.Add(stage);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
           
            stageIndex.Stages = _context.Stages.Include(s => s.Employee).Include(s => s.Performance).Include(e => e.Employee.Post);
            return View(nameof(Index), stageIndex);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var stage = await _context.Stages.FindAsync(id);

            if (stage == null)
            {
                return NotFound();
            }
            ViewData["EmployeeID"] = new SelectList(_context.Employees.Where(e => e.Role != (int)Roles.Admin), "ID", "FullName", stage.EmployeeID);
            ViewData["PerformanceID"] = new SelectList(_context.Performances, "ID", "Name", stage.PerformanceID);
            return View(stage);
        }


        [HttpPost]
        public async Task<IActionResult> Edit(int id,  Stage stage)
        {
            if (id != stage.ID)
            {
                return NotFound();
            }
            ViewData["EmployeeID"] = new SelectList(_context.Employees.Where(e => e.Role != (int)Roles.Admin), "ID", "FullName", stage.EmployeeID);
            ViewData["PerformanceID"] = new SelectList(_context.Performances, "ID", "Name", stage.PerformanceID);

           
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(stage);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StageExists(stage.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                StageIndex stageIndex = new StageIndex { Stages = _context.Stages.Include(s => s.Employee).Include(s => s.Performance)
                    .Include(e => e.Employee.Post)};
                return Json(new { isValid = true, html = Helper.RenderRazorViewToString(this, "Index", stageIndex) });
            }

            return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "Edit", stage) });
        }

     
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var stage = await _context.Stages
                .Include(s => s.Employee)
                .Include(s => s.Performance)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (stage == null)
            {
                return NotFound();
            }

            _context.Stages.Remove(stage);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

      
        private bool StageExists(int id)
        {
            return _context.Stages.Any(e => e.ID == id);
        }
    }
}

Theatre/Theatre/Controllers/TicketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Theatre.Models;

namespace Theatre.Controllers
{
    public class TicketController : Controller
    {
        private readonly DatabaseContext _context;

        public TicketController(DatabaseContext context)
        {
            _context = context;
        }


        public IActionResult Index(int role)
        {
            ViewData["PerformanceID"] = new SelectList(_context.Performances, "ID", "Name");
            ViewData["CurrentRole"] = role;
            var databaseContext = _context.Tickets.Include(t => t.Performance);
            TicketIndex ticketIndex = new TicketIndex
            {
                Tickets = databaseContext.ToList(),
                CurrentRole = role           
            };
            return View(ticketIndex);
        }

     
        [HttpPost]
        public IActionResult Create(TicketIndex ticketIndex)
        {
            bool SeatExists = _context.Tickets.Any
                (x => x.SeatNumber == ticketIndex.Ticket.SeatNumber && x.ID != ticketIndex.Ticket.ID);

            if (SeatExists)
            {
                ModelState.AddModelError("SeatNumber", "");
                ViewData["SeatExists"] = "Номер места занят";
            }

            ViewData["CurrentRole"] = ticketIndex.CurrentRole;
            if (ModelState.IsValid)
            {
                _context.Tickets.Add(ticketIndex.Ticket);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            ViewData["PerformanceID"] = new SelectList(_context.Performances, "ID", "Name", ticketIndex.Ticket.PerformanceID);
            ticketIndex.Tickets = _context.Tickets.Include(t => t.Performance);
            return View(nameof(Index), ticketIndex);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _context.Tickets.FindAsync(id);
            if (ticket == null)
            {
                return NotFound();
            }
            ViewData["PerformanceID"] = new SelectList(_context.Performances, "ID", "Name", ticket.PerformanceID);
            return View(ticket);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, Ticket ticket)
        {
            if (id != ticket.ID)
            {
                return NotFound();
            }

            bool SeatExists = _context.Tickets.Any
                (x => x.SeatNumber == ticket.SeatNumber && x.ID != ticket.ID);

            if (SeatExists)
            {
                ModelState.AddModelError("SeatNumber", "");
                ViewData["SeatExists"] = "Номер места занят";
            }


            ViewData["PerformanceID"] = new SelectList(_context.Performances, "ID", "Name", ticket.PerformanceID);

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Tickets.Update(ticket);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TicketExists(ticket.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                TicketIndex ticketIndex = new TicketIndex { Tickets = _context.Tickets.Include(t => t.Performance) };
                return Json(new { isValid = true, html = Helper.RenderRazorViewToString(this, "Index", ticketIndex) });
            }
            return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "Edit", ticket) });
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _context.Tickets
                .Include(t => t.Performance)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (ticket == null)
            {
                return NotFound();
            }

            _context.Tickets.Remove(ticket);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TicketExists(int id)
        {
            return _context.Tickets.Any(e => e.ID == id);
        }
    }
}

Theatre/Theatre/Views/Home/AdminPage.cshtml
@{ 
    Layout = null;
}
<link rel="stylesheet" href="~/css/menu.css" runat="server"/>
<div class='dashboard'>
    <div class="dashboard-nav">
        <nav class="dashboard-nav-list">
            <h1 style="text-align:center; color:white;">Театр</h1>
            <br />
            <form>
                <a asp-controller="Employee" asp-action="Index" class="dashboard-nav-item" 
                   asp-route-role="@((int)Roles.Admin)">
                    Сотрудники
                </a>
                <a asp-controller="Post" asp-action="Index" class="dashboard-nav-item" 
                   asp-route-role="@((int)Roles.Admin)">
                    Должности
                </a>
                <a asp-controller="Performance" asp-action="Index" 
                   asp-route-role="@((int)Roles.Admin)"
                   class="dashboard-nav-item">
                    Спектакли
                </a>
                <a asp-controller="Ticket" asp-action="Index" class="dashboard-nav-item" 
                   asp-route-role="@((int)Roles.Admin)">
                    Билеты
                </a>
                <a asp-controller="Membership" asp-action="Index" class="dashboard-nav-item" 
                   asp-route-role="@((int)Roles.Admin)">
                    Абонементы
                </a>
                <a asp-controller="Author" asp-action="Index" class="dashboard-nav-item" 
                   asp-route-role="@((int)Roles.Admin)">
                    Авторы
                </a>
                <a asp-controller="Stage" asp-action="Index" class="dashboard-nav-item" 
                   asp-route-role="@((int)Roles.Admin)">
                    Постановки
                </a>
            </form>
            <br />

            <a asp-action="Index" class="dashboard-nav-item"> Выйти </a>
        </nav>
    </div>
    <div class='dashboard-app'>
        <div class='dashboard-content'>
            <div class='container'>
                <div class='card'>
                    <div class='card-header'>
                        <h1>Добро пожаловать</h1>
                    </div>
                    <div class='card-body'>
                        <p>Вы зашли в систему в качестве администратора</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Theatre/Theatre/Views/Home/CashierPage.cshtml
@{
    Layout = null;
}
<link rel="stylesheet" href="~/css/menu.css" runat="server"/>
<div class='dashboard'>
    <div class="dashboard-nav">
        <nav class="dashboard-nav-list">
            <h1 style="text-align:center; color:white;">Театр</h1>
            <br />
            <form>
                <a asp-controller="Ticket" asp-action="Index" class="dashboard-nav-item"
                   asp-route-role="@((int)Roles.Cashier)">
                    Билеты
                </a>
                <a asp-controller="Membership" asp-action="Index" class="dashboard-nav-item"
                   asp-route-role="@((int)Roles.Cashier)">
                    Абонементы
                </a>
            </form>
            <br />
            <br />
            <br />

            <a asp-action="Index" class="dashboard-nav-item"> Выйти </a>
        </nav>
    </div>
    <div class='dashboard-app'>
        <div class='dashboard-content'>
            <div class='container'>
                <div class='card'>
                    <div class='card-header'>
                        <h1>Добро пожаловать</h1>
                    </div>
                    <div class='card-body'>
                        <p>Вы зашли в систему в качестве кассира</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Theatre/Theatre/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Авторизация";
}



<div style="width:15%; margin:0 auto; margin-top:150px">
    <form method="post">
        <div class="form-outline mb-4">
            <input type="text" placeholder="Логин" name="login" class="form-control" />
            <span class="text-danger">@ViewData["InvalidLogin"]</span>
        </div>

        <div class="form-outline mb-4">
            <input type="password" placeholder="Пароль" name="password" class="form-control" />
            <span class="text-danger">@ViewData["InvalidPassword"]</span>
        </div>

       
        <button type="submit" asp-action="Authorize" class="btn btn-primary btn-block">Войти</button>
    </form>
   
</div>

Theatre/Theatre/Views/Home/PerformanceDirectorPage.cshtml
@{
    Layout = null;
}
<link rel="stylesheet" href="~/css/menu.css" runat="server"/>
<div class='dashboard'>
    <div class="dashboard-nav">
        <nav class="dashboard-nav-list">
            <h1 style="text-align:center; color:white;">Театр</h1>
            <br />
            <form >              
                <a asp-controller="Performance" asp-action="Index"
                   class="dashboard-nav-item" asp-route-role="@((int)Roles.PerformanceDirector)">
                    Спектакли
                </a>                
                <a asp-controller="Author" asp-action="Index" class="dashboard-nav-item" 
                   asp-route-role="@((int)Roles.PerformanceDirector)">
                    Авторы
                </a>
                <a asp-controller="Stage" asp-action="Index" class="dashboard-nav-item" 
                   asp-route-role="@((int)Roles.PerformanceDirector)">
                    Постановки
                </a>
            </form>

            <div>
                <a asp-action="Index" class="dashboard-nav-item"> Выйти </a>
            </div>
        </nav>
    </div>
    <div class='dashboard-app'>
        <div class='dashboard-content'>
            <div class='container'>
                <div class='card'>
                    <div class='card-header'>
                        <h1>Добро пожаловать</h1>
                    </div>
                    <div class='card-body'>
                        <p>Вы зашли в систему в качестве режиссера</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Theatre/Theatre/Views/Home/TheatreDirectorPage.cshtml
@{
    Layout = null;
}
<link rel="stylesheet" href="~/css/menu.css" runat="server"/>
<div class='dashboard'>
    <div class="dashboard-nav">
        <nav class="dashboard-nav-list">
            <h1 style="text-align:center; color:white;">Театр</h1>
            <br />
            <form>
                <a asp-controller="Employee" asp-action="Index" class="dashboard-nav-item"
                   asp-route-role="@((int)Roles.TheatreDirector)">
                    Сотрудники
                </a>
                <a asp-controller="Performance" asp-action="Index"
                   asp-route-role="@((int)Roles.TheatreDirector)"
                   class="dashboard-nav-item">
                    Спектакли
                </a>
            </form>
            <br />
            <br /> <br />
            <a asp-action="Index" class="dashboard-nav-item"> Выйти </a>
        </nav>
    </div>
    <div class='dashboard-app'>
        <div class='dashboard-content'>
            <div class='container'>
                <div class='card'>
                    <div class='card-header'>
                        <h1>Добро пожаловать</h1>
                    </div>
                    <div class='card-body'>
                        <p>Вы зашли в систему в качестве директора театра</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>